version: '3.8'

services:
  odoo-extractor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoo-extractor
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./odoo-etl@gobrax-data.iam.gserviceaccount.com.json:/app/creds/odoo-etl.json:ro
    restart: "no"

